name: act-py312
channels:
  - gurobi
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - onnx
  - onnxruntime
  - pandas
  - numpy
  - networkx
  - tqdm
  - gurobi
  - ipykernel
  - matplotlib
  - pip
  - pip:
      - onnxconverter-common
      - onnxscript
      - onnx2pytorch
      - onnx-simplifier
      - transformers
      - scikit-learn